# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [ ]:
# your code goes here

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)

df.head()
df.shape
df.dtypes

Unnamed: 0                         int64
Customer                          object
State                             object
Customer Lifetime Value          float64
Response                          object
Coverage                          object
Education                         object
Effective To Date                 object
EmploymentStatus                  object
Gender                            object
Income                             int64
Location Code                     object
Marital Status                    object
Monthly Premium Auto               int64
Months Since Last Claim          float64
Months Since Policy Inception      int64
Number of Open Complaints        float64
Number of Policies                 int64
Policy Type                       object
Policy                            object
Renew Offer Type                  object
Sales Channel                     object
Total Claim Amount               float64
Vehicle Class                     object
Vehicle Size                      object
Vehicle Type                      object
dtype: object

In [5]:
df.columns = (
    df.columns
    .str.lower()
    .str.replace(" ", "_")
)
df.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type'],
      dtype='object')

In [6]:
#1. Create a DataFrame with total_claim_amount < 1000 response == "Yes"

low_claim_yes_df = df.loc[
    (df["total_claim_amount"] < 1000) &
    (df["response"] == "Yes")
]

low_claim_yes_df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [7]:
low_claim_yes_df.shape

(1399, 26)

In [10]:
#2. Average monthly premium & CLV. For customers who responded "Yes", grouped by: policy_type/ gender
#Filter customers who said “Yes”
yes_response_df = df[df["response"] == "Yes"]
#Average monthly_premium_auto
avg_premium = (
    yes_response_df
    .groupby(["policy_type", "gender"])["monthly_premium_auto"]
    .mean()
)

avg_premium

policy_type     gender
Corporate Auto  F         94.301775
                M         92.188312
Personal Auto   F         98.998148
                M         91.085821
Special Auto    F         92.314286
                M         86.343750
Name: monthly_premium_auto, dtype: float64

In [11]:
# Average customer_lifetime_value
avg_clv = (
    yes_response_df
    .groupby(["policy_type", "gender"])["customer_lifetime_value"]
    .mean()
)

avg_clv

policy_type     gender
Corporate Auto  F         7712.628736
                M         7944.465414
Personal Auto   F         8339.791842
                M         7448.383281
Special Auto    F         7691.584111
                M         8247.088702
Name: customer_lifetime_value, dtype: float64

In [12]:
#Compare with total_claim_amount
avg_claims = (
    yes_response_df
    .groupby(["policy_type", "gender"])["total_claim_amount"]
    .mean()
)

avg_claims

policy_type     gender
Corporate Auto  F         433.738499
                M         408.582459
Personal Auto   F         452.965929
                M         457.010178
Special Auto    F         453.280164
                M         429.527942
Name: total_claim_amount, dtype: float64

Segments with:
- higher customer_lifetime_value
- reasonable monthly premiums
- lower total_claim_amount
appear to be the most profitable and low-risk.

Typically, these are strong targets for future campaigns.

In [13]:
#3 Customers per state (more than 500)
#Count customers per state
state_counts = df["state"].value_counts()
state_counts

state
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: count, dtype: int64

In [14]:
#Filter states with more than 500 customers
large_states = state_counts[state_counts > 500]
large_states

state
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: count, dtype: int64

In [15]:
#4 CLV statistics by education & gender
#Group and aggregate
clv_stats = (
    df
    .groupby(["education", "gender"])["customer_lifetime_value"]
    .agg(["min", "max", "median"])
)

clv_stats

                                     min          max       median
education            gender
Bachelor             F       1904.000852  73225.95652  5640.505303
                     M       1898.007675  67907.27050  5548.031892
College              F       1898.683686  61850.18803  5623.611187
                     M       1918.119700  61134.68307  6005.847375
Doctor               F       2395.570000  44856.11397  5332.462694
                     M       2267.604038  32677.34284  5577.669457
High School or Below F       2144.921535  55277.44589  6039.553187
                     M       1940.981221  83325.38119  6286.731006
Master               F       2417.777032  51016.06704  5729.855012
                     M       2272.307310  50568.25912  5579.099207

Customers with higher education levels often show higher median CLV.

Gender differences exist, but education level appears to have a stronger

impact on customer lifetime value.

These insights can help tailor marketing and retention strategies.