# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [1]:
#Loading data
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)

df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [2]:
#dimensions of the dataset
print(df.shape)
print(df.ndim)
print(df.size)

(4008, 11)
2
44088

In [3]:
#Checking data types
df.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [4]:
#cleaning column names:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.dtypes

customer                      object
st                            object
gender                        object
education                     object
customer_lifetime_value       object
income                       float64
monthly_premium_auto         float64
number_of_open_complaints     object
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object

In [5]:
num_columns = ['customer_lifetime_value', 'income', 'monthly_premium_auto',
                'number_of_open_complaints', 'total_claim_amount']
for col in num_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dtypes

customer                      object
st                            object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints    float64
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object

In [6]:
#Number of unique values per column
df.nunique()

customer                     1071
st                              8
gender                          5
education                       6
customer_lifetime_value         0
income                        774
monthly_premium_auto          132
number_of_open_complaints       0
policy_type                     3
vehicle_class                   6
total_claim_amount            761
dtype: int64

In [7]:
#identifying categorical columns
categorical_columns = df.select_dtypes(include='object').columns
categorical_columns

Index(['customer', 'st', 'gender', 'education', 'policy_type',
       'vehicle_class'],
      dtype='object')

In [ ]:
#unique values for each categorial variable
for column in categorical_columns:
    print(f"Column: {column}")
    print("Number of unique values:", df[column].nunique())

Column: customer
Number of unique values: 1071
Column: st
Number of unique values: 8
Column: gender
Number of unique values: 5
Column: education
Number of unique values: 6
Column: policy_type
Number of unique values: 3
Column: vehicle_class
Number of unique values: 6

In [9]:
df.select_dtypes(include='number').agg(['min', 'max'])

,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount
min,NaN,0.0,61.0,NaN,0.382107
max,NaN,99960.0,35354.0,NaN,2893.239678

In [10]:
#range of values for numerical columns
df.describe()

,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount
count,0.0,1071.000000,1071.000000,0.0,1071.000000
mean,NaN,39295.701214,193.234360,NaN,404.986909
std,NaN,30469.427060,1601.190369,NaN,293.027260
min,NaN,0.000000,61.000000,NaN,0.382107
25%,NaN,14072.000000,68.000000,NaN,202.157702
50%,NaN,36234.000000,83.000000,NaN,354.729129
75%,NaN,64631.000000,109.500000,NaN,532.800000
max,NaN,99960.000000,35354.000000,NaN,2893.239678

In [11]:
stats = pd.DataFrame({
    "mean": df.mean(numeric_only=True),
    "median": df.median(numeric_only=True),
    "mode": df.mode(numeric_only=True).iloc[0],
    "std_dev": df.std(numeric_only=True)
})
stats

                                   mean        median   mode       std_dev
customer_lifetime_value             NaN           NaN    NaN           NaN
income                     39295.701214  36234.000000    0.0  30469.427060
monthly_premium_auto         193.234360     83.000000   65.0   1601.190369
number_of_open_complaints           NaN           NaN    NaN           NaN
total_claim_amount           404.986909    354.729129  321.6    293.027260

In [13]:
for col in categorical_columns:
    print(f"Value counts for {col}:")
    print(df[col].value_counts(normalize=True) * 100)
    print("-" * 40)

Value counts for customer:
customer
MY31220    0.093371
RB50392    0.093371
QZ44356    0.093371
AI49188    0.093371
WW63253    0.093371
             ...
FL50705    0.093371
WC83389    0.093371
OE15005    0.093371
FV94802    0.093371
BW63560    0.093371
Name: proportion, Length: 1071, dtype: float64
----------------------------------------
Value counts for st:
st
Oregon        29.878618
California    19.701214
Arizona       17.366947
Cali          11.204482
Nevada         9.150327
Washington     7.563025
WA             2.801120
AZ             2.334267
Name: proportion, dtype: float64
----------------------------------------
Value counts for gender:
gender
F         47.903564
M         43.291405
Male       4.088050
female     2.935010
Femal      1.781971
Name: proportion, dtype: float64
----------------------------------------
Value counts for education:
education
Bachelor                30.252101
College                 29.225023
High School or Below    27.637722
Master                   8.776844
Doctor                   3.454715
Bachelors                0.653595
Name: proportion, dtype: float64
----------------------------------------
Value counts for policy_type:
policy_type
Personal Auto     72.829132
Corporate Auto    21.848739
Special Auto       5.322129
Name: proportion, dtype: float64
----------------------------------------
Value counts for vehicle_class:
vehicle_class
Four-Door Car    53.781513
Two-Door Car     19.140990
SUV              18.580766
Sports Car        5.322129
Luxury SUV        1.867414
Luxury Car        1.307190
Name: proportion, dtype: float64
----------------------------------------

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [17]:
#pandas series with frequencies
location_counts = df['st'].value_counts()
location_counts

st
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [19]:
#top 5 ascending
location_sorted = location_counts.sort_values(ascending=True).head(5)
location_sorted

st
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [20]:
#pandas series with policy types and total sold
policy_counts = df['policy_type'].value_counts()
policy_counts

policy_type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [21]:
#undex of the maximum value
top_policy = policy_counts.idxmax()
top_policy

'Personal Auto'

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [22]:
#creating 2 dataframes
personal_auto = df.loc[df['policy_type'] == 'Personal Auto']
corporate_auto = df.loc[df['policy_type'] == 'Corporate Auto']

In [23]:
#average income
personal_auto_avg = personal_auto['income'].mean()
corporate_auto_avg = corporate_auto['income'].mean()

In [25]:
#print the results

print("Average income of Personal Auto customers:", personal_auto_avg)
print("Average income of Corporate Auto customers:", corporate_auto_avg)

Average income of Personal Auto customers: 38180.69871794872
Average income of Corporate Auto customers: 41390.31196581197

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
# Your code here